baseURL = "http://www.watbaktmarion.nl/"
languageCode = "en-us"
title = "Wat bakt marion"
theme = "dream" 

[params]
  #background = "#ddd"
  backgroundImage = "/img/background.jpg"
  linkColor = "seagreen"

  author = "Marion Sommers-Spijkerman"
  # description = ""
  avatar = "/img/me.jpg"
  motto = "Ik bak en ik blog"
  
  email = "marion.spijkerman@gmail.com"
  # github = ""
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2020

  # favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = false 
  dark404 = false
  enableRobotsTXT = true
  googleAnalytics = "UA-171121891-1"
  disqusShortname = "wat-bakt-marion"